(define-syntax lazy-cons
  (syntax-rules ()
    ((lazy-cons head tail) (cons head (delay tail)))))
(define (lazy-car collectable) (car collectable))
(define (lazy-cdr collectable) (force (cdr collectable)))
(define (lazy-head collectable size)
  (if (equal? size 0)
      '()
      (cons (lazy-car collectable) (lazy-head (lazy-cdr collectable) (- size 1)))))
(define (lazy-ref collectable index)
  (if (equal? index 0)
      (lazy-car collectable)
      (lazy-ref (lazy-cdr collectable) (- index 1))))
(define (naturals n)
  (lazy-cons n (naturals (+ n 1))))
(define (lazy-factorial n)
  (define (_iter index res)
    (lazy-cons res (_iter (+ index 1) (* res index))))
  (lazy-ref (_iter 1 1) n))
(display "naturals test:\n")
(display (lazy-head (naturals 10) 12))
(newline)
(display "factorial test:\n")
(display (lazy-factorial 10))
(newline)
(display (lazy-factorial 50))
(newline)


